'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Message_Room

    '''<summary>
    '''person_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents person_name As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''email_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_person As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''update_panel_of_stuffs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents update_panel_of_stuffs As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''repeater_message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repeater_message As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''friend_message_box_repeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friend_message_box_repeater As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''friends_message_box_repeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friends_message_box_repeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''input_link control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents input_link As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upload As Global.System.Web.UI.WebControls.Button
End Class
